# Generated by Django 5.2 on 2025-04-25 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='recruteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='api.recruteur'),
            preserve_default=False,
        ),
    ]
